### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [alekseivoroshilov/learningjava2#1]
1. Отсутствуют тесты
2. По структуре проекта, непонятно, почему корневой директорией с исходниками является `src/tail - 9`. Лучше сделать корневой `src`, а ваши классы организовать в пакет.
3. Нет поддержки ввода/вывода с консоли
4. Непонятно, зачем создавать объект класса  `Tail` только для того, чтобы вызвать один метод. Полезных полей у класса нет. Метод, делающий основную работу можно объявить статическим.
5. Название `get_tail` не соответствует принятой нотации именования методов.
6. Нет необходимости хранить весь файл в памяти. Достаточно хранить текущие N последних строк и при обработке следующей "забывать" первую из них и добавлять новую в конец. Логика работы с символами, в принципе, должна отличаться несильно. Нет необходимости считывать построчно, а затем обрабывать символы внутри строки, это ненужное усложнение логики программы. 
7. https://github.com/alekseivoroshilov/learningjava2/blob/bf28779d9513bbbb2dd331d3455797e4c16bf03c/src/tail%20-%209/tail.java#L153-L155
Ничего не понял.
8. Метод `update` я не заметил пока смотрел на занятии. Есть **гораздо** более правильный и эффективный способ дописать в конец файла, чем прочитать и заново записать его содержимое. Предлагаю поискать.

**Comment by alekseivoroshilov** [comment]
Здравствуйте! 
Исправления готовы к проверке.

**Comment by gagarski** [comment]
1. Уберите тот вывод на консоль, который не требуется согласно заданию.
2. Приведите в порядок форматирование кода везде.
3. Уберите проверку регексом для имени файла. Во-первых, сейчас под регекс не попадает абсолютный путь к файлу, во-вторых, она просто не нужна.
4. Код для чтения из консоли и из файла должен быть общим. Обратите внимание, вы везде создаёте `BufferedReader`. Сделайте функции, которые получают `tail` от произвольного `BufferedReader`а, а затем вокруг них реализуйте функциональность для файлов и для консоли. Из консоли нужно читать не до слова `exit`, а так же как и из файла, до конца (Ctrl-D в UNIX и Ctrl-Z в Windows). 
5. То же что и выше, но для записи в консоль/файл.
6. https://github.com/alekseivoroshilov/learningjava2/blob/0807bcfd1eec9230e2524545ffb2dbb868e2edd0/src/tail9/Tail.java#L47-L49
Разберитесь с документацией к `FileWriter`: когда он перезаписывает файл, а когда дописывает в него. 
7. https://github.com/alekseivoroshilov/learningjava2/blob/0807bcfd1eec9230e2524545ffb2dbb868e2edd0/src/tail9/Tail.java#L123
Вот это кажется очень странным. Почему 1, а не 0? Если это действительно должно быть так, то поясните пожалуйста.

**Comment by alekseivoroshilov** [comment]
4-пункт: Есть вопросы, попытаюсь ответить на них до встречи с вами.
7-ой пункт:  lineList.remove(1);  Единица, потому что на 0-ом элементе стоит строка с названием читаемого файла.
